version: '3' #'3.8'

services:
  apigateway:
    build:
      context: "."
      dockerfile: "src/ApiGateways/Envoy/Dockerfile"
    ports:
      - "9901:9901"
      - "10000:10000"
    
  apigatewaybffaggregator:
    build:
      context: "."
      dockerfile: "src/ApiGateways/Webshop.ApiGateways.Bff.Aggregator/Dockerfile"
    environment: 
      ASPNETCORE_ENVIRONMENT: docker
      ASPNETCORE_URLS: http://+:80

  catalogapi:
    build:
      context: "."
      dockerfile: "src/Services/Webshop.Services.Catalog.Api/Dockerfile"
    environment: 
      ASPNETCORE_Kestrel__EndPoints__Grpc__Url: http://*:81
      ASPNETCORE_Kestrel__EndPoints__Grpc__Protocols: Http2
      ASPNETCORE_Kestrel__EndPoints__WebApi__Url: http://*:80
      ASPNETCORE_Kestrel__EndPoints__WebApi__Protocols: Http1
    ports:
      - "8083:81"

  basketapi:
    build:
      context: "."
      dockerfile: "src/Services/Webshop.Services.Basket.Api/Dockerfile"
    environment: 
      ASPNETCORE_ENVIRONMENT: docker
      ASPNETCORE_Kestrel__EndPoints__Grpc__Url: http://*:81
      ASPNETCORE_Kestrel__EndPoints__Grpc__Protocols: Http2
      ASPNETCORE_Kestrel__EndPoints__WebApi__Url: http://*:80
      ASPNETCORE_Kestrel__EndPoints__WebApi__Protocols: Http1
    ports:
      - "8085:81"
    depends_on: 
      - "redis"

  redis:
    image: redis:alpine
    ports: 
      - "6379:6379"
